baseURL = 'https://p03try.github.io/'
languageCode = 'en-us'
title = 'Once it had a sence, but love has gone and leaved the void. Good luck my darlin, you will never see my smile again.'
theme = 'archie'
